// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

package chainwritertest

import (
	"github.com/goplugin/plugin-common/pkg/capabilities/targets/chainwriter"
	"github.com/goplugin/plugin-common/pkg/workflows/sdk/testutils"
)

// Target registers a new capability mock with the runner
func Target(runner *testutils.Runner, id string, fn func(input chainwriter.TargetInputs) error) *testutils.TargetMock[chainwriter.TargetInputs] {
	mock := testutils.MockTarget[chainwriter.TargetInputs](id, fn)
	runner.MockCapability(id, nil, mock)
	return mock
}
