// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

package basictargettest

import (
	"github.com/goplugin/plugin-common/pkg/capabilities/cli/cmd/testdata/fixtures/capabilities/basictarget"
	"github.com/goplugin/plugin-common/pkg/workflows/sdk/testutils"
)

// Target registers a new capability mock with the runner
func Target(runner *testutils.Runner, fn func(input basictarget.TargetInputs) error) *testutils.TargetMock[basictarget.TargetInputs] {
	mock := testutils.MockTarget[basictarget.TargetInputs]("basic-test-target@1.0.0", fn)
	runner.MockCapability("basic-test-target@1.0.0", nil, mock)
	return mock
}
